# Generated by Django 3.1.7 on 2023-01-21 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_products_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='product__image', verbose_name='Картинка цветов')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.products')),
            ],
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
