# Generated by Django 3.1.7 on 2023-01-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230121_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colork',
            name='products',
        ),
    ]
