# Generated by Django 3.1.7 on 2023-01-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230121_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='colors',
        ),
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(to='core.ColorK'),
        ),
    ]
