# Generated by Django 3.1.7 on 2023-01-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230121_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(related_name='colors', to='core.ColorK'),
        ),
    ]
