# Generated by Django 3.1.7 on 2023-01-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230121_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colork',
            name='picture',
            field=models.FileField(blank=True, db_index=True, upload_to='product__image', verbose_name='Картинка цветов'),
        ),
    ]
