# Generated by Django 3.1.7 on 2023-01-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_carouselm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='colors',
        ),
    ]
