# Generated by Django 3.1.7 on 2023-01-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230123_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.FileField(blank=True, upload_to='product_image', verbose_name='Картинки товаров'),
        ),
    ]
