# Generated by Django 4.1.5 on 2023-01-25 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_products_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colork',
            name='picture',
            field=models.ImageField(blank=True, db_index=True, upload_to='product__image', verbose_name='Картинка цветов'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=133, verbose_name='Имя заказсчика')),
                ('phone_number', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
