# Generated by Django 4.1.5 on 2023-01-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_user_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
