# Generated by Django 4.1.5 on 2023-01-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_customer_phone_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('phoneNumber', models.CharField(max_length=255, null=True)),
                ('phoneCode', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('cityAddress', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=150, null=True)),
                ('productChoosed', models.CharField(max_length=255, null=True)),
                ('colors', models.CharField(max_length=355, null=True)),
            ],
        ),
    ]
