# Generated by Django 4.1.5 on 2023-01-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='colork',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
