# Generated by Django 4.1.5 on 2023-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentMethod',
        ),
        migrations.AddField(
            model_name='order',
            name='bankCartMethod',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Банковская карта'),
        ),
        migrations.AddField(
            model_name='order',
            name='cashMethod',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Наличным способом'),
        ),
        migrations.AddField(
            model_name='order',
            name='mbank',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='МБанк'),
        ),
    ]
