# Generated by Django 4.1.5 on 2023-02-01 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_order_bankcartmethod_alter_order_cashmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cashMethod',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наличные'),
        ),
        migrations.CreateModel(
            name='infoBankCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(blank=True, default='Not found', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
    ]
