# Generated by Django 4.1.5 on 2023-02-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_order_colorscountvalue_order_colorsvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='colorsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorsItem', models.CharField(max_length=255, null=True)),
                ('colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colork', verbose_name='Расцветки')),
            ],
        ),
        migrations.DeleteModel(
            name='infoBankCart',
        ),
    ]
