# Generated by Django 4.1.5 on 2023-02-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_colorsitems_delete_infobankcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='order',
            name='colorsCountValue',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.DeleteModel(
            name='colorsItems',
        ),
    ]
